### ISSUE TITLE
Refactor the code

### ISSUE THREAD

**Issue by orhun** [orhun/dnsleaktest-tui#1]
Just... refactor it, you know? I don't like having a huge `main.rs` file. It's "speedrun quality" at best.

**Comment by bsodmike** [comment]
Also you can add Clap to accept a different host as a flag. 

But I like the way you did a speed run here. It was a bit mind boggling to go through the `heh` crate as a ratatui newbie, so this is a nice one for me to take apart to get a feel for things.

The `heh` screen handler code was super interesting.

**Comment by orhun** [comment]
> Also you can add Clap to accept a different host as a flag.

Yeah good idea :)

>  so this is a nice one for me to take apart to get a feel for things.

Good to hear that! Feel free to take this apart and refactor it btw :D

> screen handler code was super interesting.

Every Ratatui app uses a different approach when it comes to handling the screen and events. `heh` was one of those who decided to have a structured way of doing things - which turned out great for itself. I would say doing that for a smaller scale app would be too much, but `heh` is on point :)

**Comment by bsodmike** [comment]
Glad you said that as the structuring (of `heh`) takes a bit of grokking for sure!

I prefer keeping things simple when doing a speed run, like you do, and later nicely organising things etc.
